import React, { useEffect } from 'react';
import { SEO } from '../components/SEO';
import { FileText, AlertOctagon } from 'lucide-react';

export const Terms = () => {
  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  return (
    <div className="min-h-screen bg-slate-50 pt-28 pb-20 font-sans">
      <SEO title="Terms & Conditions | Janmat Bharat" description="Read the Terms and Conditions for using Janmat Bharat, an independent public opinion polling platform." canonicalPath="/terms" />

      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="bg-white rounded-xl shadow-institutional border border-slate-100 border border-slate-200 overflow-hidden">
          <div className="bg-deepNavy-900 text-white p-10 md:p-14 text-center">
            <FileText size={56} className="mx-auto mb-6 text-slate-400" />
            <h1 className="text-4xl md:text-5xl font-black mb-4">Terms & Conditions</h1>
            <p className="text-lg text-slate-400 font-medium">Last Updated: August 24, 2026</p>
          </div>

          <div className="p-8 md:p-14 prose prose-slate max-w-none prose-headings:font-black prose-headings:text-deepNavy-900">
            
            <div className="bg-red-50 border-l-4 border-red-600 p-6 rounded-r-xl mb-10">
              <h3 className="text-xl font-bold text-red-900 mt-0 flex items-center gap-2">
                <AlertOctagon size={20} /> Crucial Disclaimer
              </h3>
              <p className="text-red-800 font-medium mb-0 leading-relaxed">
                <strong>Janmat Bharat is NOT a Government Application.</strong> We are an independent, private digital opinion polling and survey platform operated by Aviraaj Digitech. We are not affiliated with, endorsed by, or connected to the Election Commission of India (ECI) or any state/central government entity. Participating in polls on this platform does NOT constitute casting an official vote in any actual election.
              </p>
            </div>

            <h2>1. Acceptance of Terms</h2>
            <p>By accessing the Janmat Bharat website or downloading our mobile application, you agree to be bound by these Terms and Conditions. If you do not agree with any part of these terms, you must discontinue use immediately.</p>

            <h2>2. Purpose of the Platform</h2>
            <p>Janmat Bharat is a platform for citizens to express their political opinions through mock polls and surveys. The analytics and results displayed are for informational and research purposes only, reflecting the sentiment of our user base, and are not official election outcomes.</p>

            <h2>3. User Conduct and Anti-Fraud Policy</h2>
            <p>To maintain the integrity of our surveys, you agree to the following:</p>
            <ul>
              <li>You will only create one account per individual and use one device to cast your vote (1 Mobile = 1 Vote).</li>
              <li>You will not use emulators, bots, automated scripts, or VPNs to manipulate polling numbers.</li>
              <li>You will not engage in hate speech, harassment, or abusive behavior in any interactive sections of the platform.</li>
            </ul>
            <p>Violation of these rules will result in immediate permanent suspension of your account and invalidation of your data.</p>

            <h2>4. Intellectual Property</h2>
            <p>All content, designs, logos, and analytics generated by the platform are the exclusive intellectual property of Aviraaj Digitech. You may not scrape, copy, or redistribute our proprietary data without explicit written permission.</p>

            <h2>5. Disclaimer of Warranties</h2>
            <p>While we strive for high accuracy in our demographic mapping and data representation, the platform is provided "AS IS". We make no guarantees regarding the absolute accuracy, reliability, or completeness of the opinion polls. Political sentiment is fluid and the data represents a specific sample size.</p>

            <h2>6. Limitation of Liability</h2>
            <p>Under no circumstances shall Aviraaj Digitech be held liable for any direct, indirect, incidental, or consequential damages arising from your use of the platform, or your reliance on the survey data provided.</p>

            <h2>7. Changes to Terms</h2>
            <p>We reserve the right to modify these terms at any time. Continued use of the platform following any changes indicates your acceptance of the new terms.</p>

            <h2>8. Contact Information</h2>
            <p>For legal inquiries or questions regarding these terms, please contact:<br/>
            <strong>Email:</strong> official@aviraajdigitech.com</p>
          </div>
        </div>
      </div>
    </div>
  );
};
